name: Bazel Test with Named Pipe

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bazel-tests:
    runs-on: ubuntu-latest
    strategy:
      # This matrix strategy splits tests across four parallel runners to speed up execution
      matrix:
        chunk: [1, 2, 3, 4]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

    #   - name: Install Bazel
    #     run: |
    #       # Update system packages and install Bazel
    #       sudo apt update
    #       sudo apt install -y bazel

      - name: Create Sample Bazel Test Directory
        run: |
          # Create a test directory and define a simple Bazel test
          mkdir -p test_dir
          cat <<EOF > test_dir/BUILD
          sh_test(
              name = "example_test",
              srcs = ["example_test.sh"],
          )
          EOF
          
          # Create a simple shell test script
          cat <<EOF > test_dir/example_test.sh
          #!/bin/bash
          echo "Running example test on chunk ${{ matrix.chunk }}"
          exit 0
          EOF
          chmod +x test_dir/example_test.sh

      - name: Set Up Named Pipe
        run: |
          # Create a named pipe for real-time log aggregation
          mkfifo combined-test-log

      - name: Run Bazel Tests in Parallel
        run: |
          # Execute Bazel tests in parallel across different matrix chunks
          # Each chunk runs separately but writes logs to the named pipe
          bazel test --test_output=all //test_dir/... | tee combined-test-log &
          wait

      - name: Upload Combined Log
        uses: actions/upload-artifact@v4
        with:
          # Upload the aggregated test log specific to each chunk
          # This allows easy debugging and review of test outputs
          name: final-test-report-chunk-${{ matrix.chunk }}
          path: combined-test-log