name: Bazel Test with Combined Log

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      # This matrix strategy splits tests across four parallel runners to simulate test execution
      matrix:
        chunk: [1, 2, 3, 4]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Sample Test Output
        run: |
          # Create a test output directory and file
          mkdir -p test_results
          
          # Generate a test file with chunk output
          echo "Test output from chunk ${{ matrix.chunk }}" >> test_results/final-test-report.log

      - name: Upload Combined Log
        uses: actions/upload-artifact@v4
        with:
          # Upload the aggregated test log
          name: final-test-report
          path: test_results/final-test-report.log
